name: my_environment
channels:
  - defaults
dependencies:
  - audioread=3.0.1
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - contourpy=1.2.0
  - cycler=0.12.1
  - decorator=5.1.1
  - filelock=3.13.1
  - fonttools=4.47.0
  - fsspec=2023.12.2
  - idna=3.6
  - Jinja2=3.1.2
  - joblib=1.3.2
  - jsonpatch=1.33
  - jsonpointer=2.4
  - kiwisolver=1.4.5
  - lazy_loader=0.3
  - librosa=0.10.1
  - llvmlite=0.41.1
  - MarkupSafe=2.1.3
  - matplotlib=3.8.2
  - mpmath=1.3.0
  - msgpack=1.0.7
  - msgpack-numpy=0.4.8
  - networkx=3.2.1
  - numba=0.58.1
  - numpy=1.26.2
  - opencv-python=4.9.0.80
  - packaging=23.2
  - pandas=2.1.4
  - Pillow=10.1.0
  - pip=23.3.2
  - platformdirs=4.1.0
  - pooch=1.8.0
  - pycparser=2.21
  - pydub=0.25.1
  - pyparsing=3.1.1
  - python-dateutil=2.8.2
  - pytorch-ignite=0.3.0
  - pytz=2023.3.post1
  - PyWavelets=1.5.0
  - requests=2.31.0
  - resampy=0.4.2
  - scikit-learn=1.3.2
  - scipy=1.11.4
  - setuptools=69.0.3
  - six=1.16.0
  - soundfile=0.12.1
  - soxr=0.3.7
  - sympy=1.12
  - termcolor=2.4.0
  - threadpoolctl=3.2.0
  - torch=2.1.2
  - torchvision=0.16.2
  - tornado=6.4
  - tqdm=4.66.1
  - typing_extensions=4.9.0
  - tzdata=2023.3
  - urllib3=2.1.0
  - visdom=0.2.4
  - websocket-client=1.7.0
  - wfdb=4.1.2
